### ISSUE TITLE
[Feature Request] Lambda Function should download CSV file with AWS SDK

### ISSUE THREAD

**Issue by unfor19** [aws-samples/aws-control-tower-automate-account-creation#5]
Hi again @kkvinjam , on another subject

Would you accept a PR that will set the following changes?

1. Instead of `URLForInputCSVFile`, the user will insert a `bucket name` and `path`, and then the user uploads a CSV file to this bucket, and the file is fetched according to given inputs
2. Provide IAM role to Lambda Function, with an IAM Policy that allows it to download any file `S3:GetObject` from the given S3 `bucket name` and `path`

I'm trying to avoid the scenario where such an important template is hosted on a public server (S3).
Let me know what you think, I'll understand if you disagree with this idea because it's a major change.

**Comment by kkvinjam** [comment]
The changes were made already and change is under review.

**Comment by cornickj** [comment]
Added in #f14199e
