### ISSUE TITLE
Lambda function times out when validating org ous

### ISSUE THREAD

**Issue by reidca** [aws-samples/aws-control-tower-automate-account-creation#7]
Firstly, thank you for creating this. It tries to solve a limitation on Control Tower which makes it unworkable for larger number of account creations. 

I used this last week to create 3 new accounts and it worked fine as expected.

Tried to use it yesterday to create 21 new accounts and find the lambda function timed out after 5 mins. At the time looking in the Dynamo table it has only inserted 8 rows.

I grabbed the cloudformation template and increased the timeout to 10 mins. This allowed it to get to 18 accounts before timing out.

Since the max is 15 mins I am going to assume that the maximum number of accounts that you can put into the csv file is approximately 20.

I think this speaks to an architecture issue. Since this is designed to be a tool for the bulk creation of accounts I don't believe it is achieving that with such limitations. The code is very sparse on logging but looking through it I am going to assume that the blocker is when validating the org ous since the other parts look very straightforward.

Perhaps step functions would be a better choice?

**Comment by saisatishkarra** [comment]
@reidca  I have made a PR and the following optimization to the lambda to process based on s3 events rather than having 
 only a batch account creation to be used once and reuse the existing lambdas based on s3 events. Also made some 
optimizations to the process account and OUs details once per lambda run instead of per s3 entry. 
 
 Probably this PR helps and provides some optimizations:
 https://github.com/aws-samples/aws-control-tower-automate-account-creation/pull/6/files
 
 Highly appreciate any review and comments.

**Comment by reidca** [comment]
> @reidca I have made a PR and the following optimization to the lambda to process based on s3 events rather than having only a batch account creation to be used once and reuse the existing lambdas based on s3 events. Also made some optimizations to the process account and OUs details once per lambda run instead of per s3 entry.
> 
> Probably this PR helps and provides some optimizations: https://github.com/aws-samples/aws-control-tower-automate-account-creation/pull/6/files
> 
> Highly appreciate any review and comments.

Thank you for your response and time on this issue.

I have used your fork here: https://github.com/Kong/aws-control-tower-automate-account-creation/tree/feat/s3-event-driven-updates

I have uploaded the new Lambda files and the csv file with the account details in however this does not appear to be working.
Looking at the Lambda monitoring, it seems that the Lambda functions are not being invoked.

The DynamoDB table is not getting populated from the CSV file. I cannot see any errors because the Lambdas are simply not being executed.

How is the DynamoDB table meant to get populated from the CSV file?

**Comment by saisatishkarra** [comment]
Hi @reidca https://github.com/Kong/aws-control-tower-automate-account-creation/blob/feat/s3-event-driven-updates/BatchAccountCreation.yaml#L109-L115 is the event trigger to launch lambda when there is upload in s3. 

One probable cause could be that when you used the [BatchAccountCreation.yaml](https://github.com/Kong/aws-control-tower-automate-account-creation/blob/feat/s3-event-driven-updates/BatchAccountCreation.yaml#L92) to launch the infra, it is trying to use the lambda code from existing AWS sample bucket zip files which wouldn't have mthe lambda changes I have made.

I had to keep this the same assuming the PR would be merged in the future.

As an alternative, you should have to fork the repo, change the default s3 sample bucket name in CF template and upload the zip files of lambda code in the forked branch to your s3 bucket and launch the stack.

**Comment by saisatishkarra** [comment]
Did you try to isolate the issue to trigger the lambda manually and see if that actually does the rest of the job? This is to isolate if the s3 lambda event is working or not?

**Comment by saisatishkarra** [comment]
I don't have an AWS account to test the creation, unfortunately.

**Comment by kkvinjam** [comment]
@reidca Thanks for the detailed explanation. Let me investigate what's happening with timing here. Will get back on it soon.

**Comment by reidca** [comment]
> @reidca Thanks for the detailed explanation. Let me investigate what's happening with timing here. Will get back on it soon.

Thanks for looking. I have now created over 50 account using this but I have found the max batch size to be 20 with a timeout of 900 seconds. This is due to the validation phase. If that Lambda times out the entire cloud formation stack rolls back.

**Comment by reidca** [comment]
> @reidca Thanks for the detailed explanation. Let me investigate what's happening with timing here. Will get back on it soon.

any news on this?

**Comment by kkvinjam** [comment]
Issue resolved with check in ef102f092992902615d233f5eb8328be20e1978f
